[package]
name = "bin-reader"
license = "MIT"
description = "Binary Reader from multi source"
readme = "README.md"
repository = "https://github.com/mith-mmk/bin-reader"
edition = "2021"
rust-version = "1.58"
version = "0.0.1"

[features]
default = []
stream = []
codec = ["encoding_rs"]
async = ["tokio","async-trait"]

[dependencies]
encoding_rs = {version = "0.8",optional = true}
async-trait = {version = "0.1.36",optional = true}
tokio = {version = "1", optional = true}
